baseURL = 'samira-the-rogue-gnome.github.io'
languageCode = 'en-us'
title = 'My DnD Adventures'
theme = 'hugo-story'
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir = "public"
staticDir = "static"

